### ISSUE TITLE
Blocklog won't compile

### ISSUE THREAD

**Issue by funnybunnyofdoom** [funnybunnyofdoom/Vintage-Story-Mods#215]
```23.5.2023 13:36:16 [Server Error] [blocklog] CS0234: The type or namespace name 'Formatters' does not exist in the namespace 'System.Runtime.Serialization' (are you missing an assembly reference?)
23.5.2023 13:36:16 [Server Notification] [blocklog] Successfully compiled 1 source files```
and i ran /blocklog with the response "command not found"

**Comment by radfast** [comment]
Hey @funnybunnyofdoom 

There's an issue when `blocklog` is present in a [.NET7 build of 1.18.5 for Linux](https://discord.com/channels/302152934249070593/1110493590167228416), also a compilation error.

I believe it is likely the issue is simply your `using` statements.  Some of them are unused, and one of them - `Vintagestory.Essentials` should not be present at all, it is a namespace which is only relevant to pathfinding.

Hope that helps, it would be really great if you can make a 1.18.5 build and check that it loads OK (no compilation error) under a .NET7 build for Vintage Story, as we hope to have the official .NET7 build out very soon and we will then be encouraging server owners to migrate to .NET7 for performance reasons and ease of maintenance.

**Comment by radfast** [comment]
> There's an issue when blocklog is present in a [.NET7 build of 1.18.5 for Linux](https://discord.com/channels/302152934249070593/1110493590167228416), also a compilation error.

```23.5.2023 13:25:39 [Server Error] [blocklog] CS0234: The type or namespace name 'Formatters' does not exist in the namespace 'System.Runtime.Serialization' (are you missing an assembly reference?)```

That error makes no sense as `System.Runtime.Serialization.Formatters` definitely does exist.  Anyhow, it is another example of a `using` statement which is not in fact being used, so I am hopeful that cleaning that up will fix the issue

**Comment by funnybunnyofdoom** [comment]
@radfast 
Removed the redundant using statements. Unsure how to test on NET7 but I asked for assistance on the official discord.
